---

- name: Create Workshop environment
  hosts: localhost
  connection: local
  tasks:
    - name: Get package facts
      ansible.builtin.package_facts:

    - name: Install Podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true
      when: ansible_facts.packages.podman is not defined

    - name: Pull image for managed node containers
      containers.podman.podman_image:
        name: docker.io/timgrt/rockylinux8-ansible

    - name: Start managed node containers, publish 3 ports for each container
      containers.podman.podman_container:
        name: "{{ item }}"
        image: docker.io/timgrt/rockylinux8-ansible:latest
        hostname: "{{ item }}"
        ports:
          - "{{ hostvars[item]['ssh_port'] }}:22"
          - "{{ hostvars[item]['webserver_port1'] }}:80"
          - "{{ hostvars[item]['webserver_port2'] }}:8080"
        stop_signal: 15
        state: started
      loop: "{{ groups['managed_nodes'] }}"

    - name: Create folder for workshop inventory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/lab_inventory"
        state: directory
        mode: "0755"

    - name: Create workshop inventory file
      ansible.builtin.template:
        src: workshop-inventory.ini.j2
        dest: "{{ ansible_user_dir }}/lab_inventory/hosts"
        mode: "0644"

    - name: Update localhost in /etc/hosts to resolve all managed node containers
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "\\g<1> {{ groups['managed_nodes'] | join(' ') }}"
        regexp: "^(127\\.0\\.0\\.1.*)$"
        backrefs: true
      become: true
      tags: test
    
    - name: Add block to ssh_config for easy SSH access to managed nodes
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'ssh-config.j2') }}"
        path: "{{ ansible_user_dir }}/.ssh/config"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR WORKSHOP ENVIRONMENT"
        
    - name: Deploy ansible.cfg to home directory
      ansible.builtin.template:
        src: "ansible.cfg"
        dest: "{{ ansible_user_dir }}/.ansible.cfg"
        mode: "0644"

    - name: Create OpenSSH keypair for accessing managed nodes
      community.crypto.openssh_keypair:
        path: "{{ ansible_user_dir }}/.ssh/workshop"

- name: Prepare managed nodes
  hosts: managed_nodes
  connection: podman
  tasks:
    - name: Install SSH daemon
      ansible.builtin.package:
        name: openssh-server
        state: present

    - name: Start SSH daemon
      ansible.builtin.service:
        name: sshd
        state: started

    - name: Remove /run/nologin to be able to login as unprivileged user
      ansible.builtin.file:
        path: /run/nologin
        state: absent

    - name: Add public key of workshop SSH keypair to authorized_keys of ansible user
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/' ~ lookup('env', 'USER') ~ '/.ssh/workshop.pub') }}"
        state: present
      become: true
      become_user: ansible
