---

- name: Create Workshop environment
  hosts: localhost
  connection: local
  tasks:
    - name: Get package facts
      ansible.builtin.package_facts:

    - name: Install Podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true
      when: ansible_facts.packages.podman is not defined

    - name: Pull image for managed node containers
      containers.podman.podman_image:
        name: docker.io/timgrt/rockylinux8-ansible

    - name: Start managed node containers, publish 3 ports for each container
      containers.podman.podman_container:
        name: "{{ item }}"
        image: docker.io/timgrt/rockylinux8-ansible:latest
        hostname: "{{ item }}"
        ports:
          - "{{ hostvars[item]['ssh_port'] }}:22"
          - "{{ hostvars[item]['webserver_port1'] }}:80"
          - "{{ hostvars[item]['webserver_port2'] }}:8080"
        stop_signal: 15
        state: started
      loop: "{{ groups['managed_nodes'] }}"

    - name: Create folder for workshop inventory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/lab_inventory"
        state: directory
        mode: "0755"

    - name: Create workshop inventory file
      ansible.builtin.template:
        src: workshop-inventory.ini.j2
        dest: "{{ ansible_user_dir }}/lab_inventory/hosts"
        mode: "0644"

    - name: Add block to ssh_config for easy SSH access to managed nodes # noqa risky-file-permissions
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'ssh-config.j2') }}"
        path: "{{ ansible_user_dir }}/.ssh/config"
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR WORKSHOP ENVIRONMENT"

    - name: Deploy ansible.cfg to home directory
      ansible.builtin.template:
        src: "ansible.cfg"
        dest: "{{ ansible_user_dir }}/.ansible.cfg"
        mode: "0644"
        backup: true
      register: config_deployment

    - name: Backup file of .ansible.cfg created
      ansible.builtin.debug:
        msg: Backup file at "{{ config_deployment.backup_file }}"
      when: config_deployment.backup_file is defined

    - name: Check for existing SSH keypair
      ansible.builtin.find:
        path: "{{ ansible_user_dir }}/.ssh"
        file_type: file
        patterns: ansible-workshop-environment*
      register: find_keypair

    - name: Keypair was found
      when: find_keypair.matched != 0
      block:
        - name: Check if OpenSSH keypair does not match target configuration
          community.crypto.openssh_keypair:
            path: "{{ ansible_user_dir }}/.ssh/ansible-workshop-environment"
            comment: Ansible generated, for accessing managed node containers of Ansible Workshop
          check_mode: true
          register: keypair_creation_check

        - name: Abort playbook if keypair was found and does not match target configuration # noqa no-handler
          ansible.builtin.fail:
            msg: |
              A keypair 'ansible-workshop-environment' already exists but does match the desired config!
              The keypair was not created by this playbook.
              The 'delete-workshop-environment' playbook WILL REMOVE this key!
              MOVE THE KEY MANUALLY BEFORE RUNNING THIS PLAYBOOK AGAIN OR ANY OTHER FROM THIS PROJECT!
          when: keypair_creation_check.changed

    - name: Create OpenSSH keypair for accessing managed nodes
      community.crypto.openssh_keypair:
        path: "{{ ansible_user_dir }}/.ssh/ansible-workshop-environment"
        comment: Ansible generated, for accessing managed node containers of Ansible Workshop

- name: Prepare managed nodes
  hosts: managed_nodes
  connection: podman
  tasks:
    - name: Install SSH daemon
      ansible.builtin.package:
        name: openssh-server
        state: present

    - name: Start SSH daemon
      ansible.builtin.service:
        name: sshd
        state: started

    - name: Remove /run/nologin to be able to login as unprivileged user
      ansible.builtin.file:
        path: /run/nologin
        state: absent

    - name: Add public key of workshop SSH keypair to authorized_keys of ansible user
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/' ~ lookup('env', 'USER') ~ '/.ssh/ansible-workshop-environment.pub') }}"
        state: present
      become: true
      become_user: ansible
