---

- name: Delete Workshop environment
  hosts: localhost
  connection: local
  tasks:
    - name: Delete managed node containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['managed_nodes'] }}"

    - name: Delete folder with workshop inventory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/lab_inventory"
        state: absent

    - name: Remove managed nodes from localhost in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "\\1"
        regexp: "^(127\\.0\\.0\\.1.*)( {{ groups['managed_nodes'] | join(' ') }})$$"
        backrefs: true
      become: true

    - name: Remove managed nodes from known_hosts
      ansible.builtin.known_hosts:
        path: "{{ ansible_user_dir }}/.ssh/known_hosts"
        name: "[localhost]:{{ hostvars[item]['ssh_port'] }}]"
        state: absent
      loop: "{{ groups['managed_nodes'] }}"
    
    - name: Delete block from ssh_config
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'ssh-config.j2') }}"
        path: "{{ ansible_user_dir }}/.ssh/config"
        state: absent
    
    - name: Delete ansible.cfg from home directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.ansible.cfg"
        state: absent
